
CREATE TABLE IF NOT EXISTS ROLES
(
    ROLE_ID BIGSERIAL PRIMARY KEY,
    ROLE_NAME VARCHAR(255) NOT NULL

);

CREATE TABLE IF NOT EXISTS ITEMS
(
    ITEM_ID BIGSERIAL PRIMARY KEY,
    ITEM_NOME VARCHAR(255) NOT NULL,
    ITEM_DESC VARCHAR(255) NOT NULL,
    ITEM_VALOR FLOAT NOT NULL

);
CREATE TABLE IF NOT EXISTS USERS
(
    USER_ID BIGSERIAL PRIMARY KEY,
    ENABLE BOOLEAN NOT NULL,
    USER_EMAIL VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(255) NOT NULL,
    USER_PASSWORD VARCHAR(255),
    USER_CARRINHO BIGINT

    --CONSTRAINT FK_user_roles FOREIGN KEY (USER_ID) REFERENCES ROLES(ROLE_ID)
    );

CREATE TABLE IF NOT EXISTS CARRINHO_CLIENTE
(
    CARRINHO_ID BIGSERIAL PRIMARY KEY,
    CARRINHO_USER_ID BIGINT,
    CARRINHO_VALOR_TOTAL double precision NOT NULL,

    CONSTRAINT FK_CARRINHO_USER FOREIGN KEY (CARRINHO_USER_ID) REFERENCES USERS(USER_ID)
    --CONSTRAINT FK_ITEM_CARRINHO FOREIGN KEY ITEM_CARRINHO_ID REFERENCES ITEMS_CARRINHO
);

CREATE TABLE IF NOT EXISTS ITEMS_CARRINHO
(
    ITEM_CARRINHO_ID BIGSERIAL PRIMARY KEY,
    ITEM_CARRINHO_ITEM BIGINT NOT NULL,
    ITEM_CARRINHO_ITEM_QTD BIGINT NOT NULL,
    ITEM_CARRINHO_CARRINHO_ID BIGINT NOT NULL,

    --CONSTRAINT FK_CARRINHO_ITEM FOREIGN KEY (ITEM_CARRINHO_CARRINHO_ID) REFERENCES CARRINHO_CLIENTE(CARRINHO_ID),
    CONSTRAINT FK_CARRINHO_ITEM FOREIGN KEY (ITEM_CARRINHO_CARRINHO_ID) REFERENCES CARRINHO_CLIENTE(CARRINHO_ID),
    CONSTRAINT FK_ITEM_CARRINHO FOREIGN KEY (ITEM_CARRINHO_ITEM) REFERENCES ITEMS(ITEM_ID)
);

CREATE TABLE IF NOT EXISTS USER_ROLES
(
    ROLE_ID BIGINT NOT NULL,
    USER_ID BIGINT NOT NULL,

    CONSTRAINT FK_ROLE_USER FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ROLE_ID),
    CONSTRAINT FK_USER_ROLE FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);

